/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steamcipher;

import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author AngleOfPeace
 */
public class A51 extends javax.swing.JFrame {

    /**
     * Creates new form A51
     */
    public A51() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtM = new javax.swing.JTextField();
        TxtK = new javax.swing.JTextField();
        TxtKQ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Mahoa = new javax.swing.JButton();
        Giaima = new javax.swing.JButton();
        Import = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A5/1");

        jLabel1.setText("Message");

        jLabel2.setText("Key(64bit)");

        jLabel3.setText("Kết quả");

        Mahoa.setText("Mã hóa");
        Mahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MahoaActionPerformed(evt);
            }
        });

        Giaima.setText("Giải mã");
        Giaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiaimaActionPerformed(evt);
            }
        });

        Import.setText("Import(.txt)");
        Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtKQ)
                            .addComponent(TxtM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Mahoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Giaima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Import)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Giaima)
                    .addComponent(Mahoa)
                    .addComponent(Import))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MahoaActionPerformed
        StringBuilder s=new StringBuilder();
        String mes=TxtM.getText();
        String key=TxtK.getText();
         for(int u:DeEncrypt(mes,key))
            {
                    s.append(u);
            }
        TxtKQ.setText(s.toString());
    }//GEN-LAST:event_MahoaActionPerformed

    private void GiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiaimaActionPerformed
        StringBuilder s=new StringBuilder();
        String mes=TxtM.getText();
        String key=TxtK.getText();
         for(int u:DeEncrypt(mes,key))
            {
                    s.append(u);
            }
        TxtKQ.setText(s.toString());
    }//GEN-LAST:event_GiaimaActionPerformed

    private void ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportActionPerformed
        FileDialog dialog = new FileDialog((Frame)null, "Select File to Open", FileDialog.LOAD);
        dialog.setFile("*.txt");
        dialog.setVisible(true);
       File myObj = new File(dialog.getDirectory()+"\\"+dialog.getFile());
        if (myObj.exists()){
            try {
                Scanner sc = new Scanner(myObj);
                sc.useDelimiter("\\Z");
                TxtM.setText(sc.nextLine());
                TxtK.setText(sc.nextLine());
            } catch (FileNotFoundException ex) {
                 TxtM.setText("The file does not exist.");
                }
        }
    }//GEN-LAST:event_ImportActionPerformed

    public int[] XoayX(int[] x){
          int i;
          int t = x[13]^x[16]^x[17]^x[18];
          for(i=18; i>0; i--)
          {
              x[i] = x[i-1];
              x[0] = t;
          }
          return x;
    }
     public int[] XoayY(int[] y){
         int i;
         int t = y[20]^y[21];    
         for(i=21; i>0; i--)
         { 
           y[i] = y[i-1];
           y[0] = t;
         }
         return y;
     }
     public int[] XoayZ(int[] z){
         int i;
         int t = z[7]^z[20]^z[21]^z[22];
         for(i=22; i>0; i--)
         {
            z[i] = z[i-1];
            z[0] = t;
         }
         return z;
     }
     public int[] major(String mes,String key)
     {
        String str[]=key.split("");
        int s[] = new int[mes.length()];
        int i;
        int x[] = new int[19];
        int y[] = new int[22];
        int z[] = new int[23];
        
        for(i=0; i<19; i++)
                x[i] = Integer.parseInt(str[i]);

            for(i=0; i<22; i++)
                y[i] = Integer.parseInt(str[i+19]);

            for(i=0; i<23; i++)
                z[i] = Integer.parseInt(str[i+19+22]);

            int m = 0;
         for(int j=0; j<mes.length(); j++) 
         {
             if(x[8]==y[10] || x[8]==z[10])
                    m = x[8];
                else if(y[10]==z[10])
                    m = y[10];
             if(x[8]==m)
             {
                XoayX(x);
             }
             if(y[10]==m) 
             {
                XoayY(y); 
             }
             if(z[10]==m)
             {
                XoayZ(z);
             }
             s[j] = x[18]^y[21]^z[22];
         }
         return s;
     }
     public int[] DeEncrypt(String mes,String key){
         int enc[] = new int[mes.length()];
         for(int i=0; i<mes.length(); i++) 
         { 
            enc[i] = Integer.parseInt(Character.toString(mes.charAt(i)))^major(mes,key)[i];  
         }
         return enc;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A51.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A51.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A51.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A51.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A51().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Giaima;
    private javax.swing.JButton Import;
    private javax.swing.JButton Mahoa;
    private javax.swing.JTextField TxtK;
    private javax.swing.JTextField TxtKQ;
    private javax.swing.JTextField TxtM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
